name: adpro
channels:
  - defaults
dependencies:
  - geopandas=0.12.2
  - ipykernel=6.19.2
  - ipython=8.10.0
  - jupyter_client=7.4.9
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.9.16
  - seaborn=0.12.2
  - setuptools=65.6.3
  - statsmodels==0.13.5